apiVersion: v1
kind: ConfigMap
metadata:
  name: module-config
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: example/*
      urlPathTemplate: http://statefunxp.default/v1/functions
      transport:
        timeouts:
          call: 2min
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: example/in
      address: dev-cluster-kafka-bootstrap.kafka:9092
      consumerGroupId: statefun-ingress
      topics:
        - topic: topic1
          valueType: example/MyMessage
          targets:
            - example/hello
